export const ROUTES = {
    main: '/',
    auth: '/auth',
    registration: '/registration',
    recovery: '/forgot-pass',
    profile: '/profile',
    allCategories: '/books/all',
    bookCategory: '/books/:category',
    terms: '/terms',
    contract: '/contract',
    bookDetail: '/books/:category/:bookId',
    admin: '/admin',
    adminProfile: '/admin/profile',
    adminBooks: '/admin/books',
    adminBookDetail: '/admin/books/:bookId',
    adminParagraph: '/admin/:paragraph',
    adminUser: '/admin/users/:id',
};
